// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSmVJ6MW70qnx7dfF9AUuLKcLEew_Cypg',
    appId: '1:809075012266:web:ff928b3ce9deaae181d6d3',
    messagingSenderId: '809075012266',
    projectId: 'database-51576',
    authDomain: 'database-51576.firebaseapp.com',
    storageBucket: 'database-51576.firebasestorage.app',
    measurementId: 'G-NQ555MY637',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpJxVhgaDACT2qshY9YccqXfoGAZ4qLts',
    appId: '1:809075012266:android:496f8d465538f97681d6d3',
    messagingSenderId: '809075012266',
    projectId: 'database-51576',
    storageBucket: 'database-51576.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMy2LiwV6octe4sZ-U6d2Ue_R8YlP2n1o',
    appId: '1:809075012266:ios:bcea18944a03916d81d6d3',
    messagingSenderId: '809075012266',
    projectId: 'database-51576',
    storageBucket: 'database-51576.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMy2LiwV6octe4sZ-U6d2Ue_R8YlP2n1o',
    appId: '1:809075012266:ios:bcea18944a03916d81d6d3',
    messagingSenderId: '809075012266',
    projectId: 'database-51576',
    storageBucket: 'database-51576.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSmVJ6MW70qnx7dfF9AUuLKcLEew_Cypg',
    appId: '1:809075012266:web:8cca9c4ed968c4e181d6d3',
    messagingSenderId: '809075012266',
    projectId: 'database-51576',
    authDomain: 'database-51576.firebaseapp.com',
    storageBucket: 'database-51576.firebasestorage.app',
    measurementId: 'G-TRPRXCS50M',
  );

}